### ISSUE TITLE
Jenkins Build 시 "java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.LinuxNativeDispatcher" 발생

### ISSUE THREAD

**Issue by pshee23** [pshee23/TIL#2]
jenkins 빌드 시 다음과 같은 에러 발생

``` 
java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.LinuxNativeDispatcher
	at sun.nio.fs.LinuxFileSystem.getMountEntries(LinuxFileSystem.java:81)
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:70)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
	at java.nio.file.Files.getFileStore(Files.java:1461)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.getFileStoreAttributes(FS.java:362)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.get(FS.java:346)
	at org.eclipse.jgit.util.FS.getFileStoreAttributes(FS.java:913)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:226)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:207)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:104)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:205)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:625)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getRepository(CliGitAPIImpl.java:3410)
	at hudson.plugins.git.GitAPI.getRepository(GitAPI.java:288)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:28)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:84)
	at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1426)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1366)
	at hudson.scm.SCM.checkout(SCM.java:540)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1217)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:647)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:519)
	at hudson.model.Run.execute(Run.java:1897)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
SSH: Current build result is [FAILURE], not going to run.
```

**Comment by pshee23** [comment]
Jenkins running 중 자바 업데이트로 인한 symLink오류 등 연결 오류가 있었던 듯 함.

재시작을 하거나 재설치 권장

나는 재시작을 해서 해결 했다. restart가 아닌 stop & start로 진행하길 권장

```
$ /etc/init.d/jenkins stop
$ /etc/init.d/jenkins start
```
